kind: pipeline
name: default

# workspace:
#   base: /go
#   path: 

steps:
- name: test
  image: golang:1.11
  commands:
    - "go test ./..."
- name: build
  image: plugins/docker
  settings:
    repo: quiz-api
    tags:
    - latest
  volumes:
  - name: docker-sock
    path: /var/run/docker.sock

volumes:
- name: docker-sock
  host:
    path: /var/run/docker.sock
