kind: pipeline
name: default

steps:
- name: test
  image: golang:1.11
  commands:
    - "go test ./..."
- name: build
  image: plugins/docker
  settings:
    pull: false
    target: production
    repo: quiz-api
    tags:
      - latest
 
