kind: pipeline
name: default

steps:
- name: test
  image: golang:1.11
  commands:
    - "go test ./..."
- name: build
  image: plugins/docker
  volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  settings:
    repo: quiz-api
    tags:
      - latest
 
