version: "3"

services:
  mongo:
    container_name: mongo
    image: mongo:3.2.10
    ports:
    - "27018:27017"
    expose:
    - 27018
  quiz-service:
    image: quiz-service:latest
    ports:
    - "3000:3000"
    environment:
    - MONGO_URL=mongodb://mongo:27017
    expose:
    - 3000
    logging:
      driver: "json-file"
      options:
        max-size: "8k"